# Generated by Django 3.2.7 on 2021-10-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobertmodel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeling',
        ),
    ]
